In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[5.5255e+30, 4.5608e-41, 5.5255e+30],
        [4.5608e-41, 1.1541e-36, 4.5608e-41],
        [1.3593e-43, 0.0000e+00, 5.5255e+30],
        [4.5608e-41, 5.5255e+30, 4.5608e-41],
        [5.5255e+30, 4.5608e-41, 2.8067e-37]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4998, 0.5924, 0.4032],
        [0.8648, 0.3387, 0.5972],
        [0.1464, 0.6277, 0.7306],
        [0.4668, 0.3468, 0.8859],
        [0.0705, 0.9056, 0.0203]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double) # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
x = torch.randn_like(x, dtype=torch.float) # override dtype!
print(x)
print(x.size()) # torch.Size is in fact a tuple

tensor([[-0.0515,  0.2944, -0.2991],
        [-0.4911, -2.2893, -0.7314],
        [ 0.9025,  0.5694,  0.0750],
        [ 0.5577,  0.1023, -0.1166],
        [-1.6606,  0.1532, -0.8488]])
torch.Size([5, 3])


In [13]:
# Operations
y = torch.rand(5, 3)
print(x+y)
print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# in-place, Any operation that mutates a tensor in-place is post-fixed with an _. 
# For example: x.copy_(y), x.t_(), will change x.
y.add_(x)
print(y)

tensor([[ 0.4715,  0.6931,  0.6375],
        [-0.2920, -1.9957, -0.2832],
        [ 1.6685,  1.2711,  0.6254],
        [ 0.5999,  0.3451,  0.7691],
        [-1.6115,  0.6577, -0.2159]])
tensor([[ 0.4715,  0.6931,  0.6375],
        [-0.2920, -1.9957, -0.2832],
        [ 1.6685,  1.2711,  0.6254],
        [ 0.5999,  0.3451,  0.7691],
        [-1.6115,  0.6577, -0.2159]])
tensor([[ 0.4715,  0.6931,  0.6375],
        [-0.2920, -1.9957, -0.2832],
        [ 1.6685,  1.2711,  0.6254],
        [ 0.5999,  0.3451,  0.7691],
        [-1.6115,  0.6577, -0.2159]])
tensor([[ 0.4715,  0.6931,  0.6375],
        [-0.2920, -1.9957, -0.2832],
        [ 1.6685,  1.2711,  0.6254],
        [ 0.5999,  0.3451,  0.7691],
        [-1.6115,  0.6577, -0.2159]])


In [14]:
print(x[:, 1])

tensor([ 0.2944, -2.2893,  0.5694,  0.1023,  0.1532])


In [15]:
# resize
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.1168])
1.1168403625488281


In [17]:
# NumPy Bridge
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [22]:
# CUDA Tensors
if torch.cuda.is_available():
    device = torch.device("cuda") # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)  # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([2.1168], device='cuda:0')
tensor([2.1168], dtype=torch.float64)
